//go:build !ignore_autogenerated 
// +build !ignore_autogenerated

// This file was generated by gen-errfuncs.  DO NOT EDIT.

package gohar

import (
	"errors"
	"fmt"
)
 
func NonPrintableAlteration(err error) error {
	return errors.Join(ErrNonPrintableAlteration, err)
}

func NonPrintableAlterationf(msg string, args ...any) error {
	return fmt.Errorf("%w: %s", ErrNonPrintableAlteration, fmt.Sprintf(msg, args...))
}
 
func UnknownScalePattern(err error) error {
	return errors.Join(ErrUnknownScalePattern, err)
}

func UnknownScalePatternf(msg string, args ...any) error {
	return fmt.Errorf("%w: %s", ErrUnknownScalePattern, fmt.Sprintf(msg, args...))
}
 
func InvalidDegree(err error) error {
	return errors.Join(ErrInvalidDegree, err)
}

func InvalidDegreef(msg string, args ...any) error {
	return fmt.Errorf("%w: %s", ErrInvalidDegree, fmt.Sprintf(msg, args...))
}
 
func BufferOverflow(err error) error {
	return errors.Join(ErrBufferOverflow, err)
}

func BufferOverflowf(msg string, args ...any) error {
	return fmt.Errorf("%w: %s", ErrBufferOverflow, fmt.Sprintf(msg, args...))
}
 
func NilBuffer(err error) error {
	return errors.Join(ErrNilBuffer, err)
}

func NilBufferf(msg string, args ...any) error {
	return fmt.Errorf("%w: %s", ErrNilBuffer, fmt.Sprintf(msg, args...))
}
 
func InvalidBaseNote(err error) error {
	return errors.Join(ErrInvalidBaseNote, err)
}

func InvalidBaseNotef(msg string, args ...any) error {
	return fmt.Errorf("%w: %s", ErrInvalidBaseNote, fmt.Sprintf(msg, args...))
}
